# Generated by Django 2.2.7 on 2020-07-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Div1LongA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
    ]
