# Generated by Django 2.2.7 on 2020-07-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('long', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Div1LongB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div1LongC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div1LongD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div1LongE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div1LongF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div1LongG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div1LongH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div1LongI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div1LongJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Div2LongJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('contest', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submissions', models.IntegerField(default=0)),
            ],
        ),
    ]
