# Generated by Django 2.2.7 on 2020-07-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('long', '0002_div1longb_div1longc_div1longd_div1longe_div1longf_div1longg_div1longh_div1longi_div1longj_div2longa_'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Div1LongD',
            new_name='Div1A',
        ),
        migrations.RenameModel(
            old_name='Div1LongC',
            new_name='Div1B',
        ),
        migrations.RenameModel(
            old_name='Div2LongA',
            new_name='Div1C',
        ),
        migrations.RenameModel(
            old_name='Div1LongB',
            new_name='Div1D',
        ),
        migrations.RenameModel(
            old_name='Div2LongD',
            new_name='Div1E',
        ),
        migrations.RenameModel(
            old_name='Div1LongA',
            new_name='Div1F',
        ),
        migrations.RenameModel(
            old_name='Div2LongB',
            new_name='Div1G',
        ),
        migrations.RenameModel(
            old_name='Div2LongF',
            new_name='Div1H',
        ),
        migrations.RenameModel(
            old_name='Div1LongG',
            new_name='Div1I',
        ),
        migrations.RenameModel(
            old_name='Div2LongH',
            new_name='Div1J',
        ),
        migrations.RenameModel(
            old_name='Div2LongI',
            new_name='Div2A',
        ),
        migrations.RenameModel(
            old_name='Div1LongI',
            new_name='Div2B',
        ),
        migrations.RenameModel(
            old_name='Div1LongJ',
            new_name='Div2C',
        ),
        migrations.RenameModel(
            old_name='Div2LongJ',
            new_name='Div2D',
        ),
        migrations.RenameModel(
            old_name='Div1LongF',
            new_name='Div2E',
        ),
        migrations.RenameModel(
            old_name='Div1LongH',
            new_name='Div2F',
        ),
        migrations.RenameModel(
            old_name='Div2LongE',
            new_name='Div2G',
        ),
        migrations.RenameModel(
            old_name='Div2LongG',
            new_name='Div2H',
        ),
        migrations.RenameModel(
            old_name='Div2LongC',
            new_name='Div2I',
        ),
        migrations.RenameModel(
            old_name='Div1LongE',
            new_name='Div2J',
        ),
    ]
