# Generated by Django 2.2.7 on 2020-07-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_time', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Div1H',
        ),
        migrations.DeleteModel(
            name='Div1I',
        ),
        migrations.DeleteModel(
            name='Div1J',
        ),
        migrations.DeleteModel(
            name='Div2H',
        ),
        migrations.DeleteModel(
            name='Div2I',
        ),
        migrations.DeleteModel(
            name='Div2J',
        ),
    ]
