# Generated by Django 2.2.7 on 2020-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch_time', '0002_auto_20200719_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='div1a',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div1b',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div1c',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div1d',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div1e',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div1f',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div1g',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div2a',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div2b',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div2c',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div2d',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div2e',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div2f',
            name='link',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='div2g',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
